version: "3"

services:
  softether-server:
    image: siomiz/softethervpn
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 5555:5555/tcp
    container_name: softether-server
    environment:
      - USERS=${VPN_USERS}
      - PSK=${VPN_KEY}
    privileged: true
    restart: always
    networks:
      - vpn_default

networks:
  vpn_default:
    external: true
    name: vpn_default
